package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"

	"example.com/parserjson/structure"
)

func getText(data structure.AutoGenerated) string {
	text := "text: "
	for i := 0; i < len(data.Response.Chunks); i++ {
		if data.Response.Chunks[i].ChannelTag == "1" {
			for j := 0; j < len(data.Response.Chunks[i].Alternatives); j++ {
				text += "\n" + data.Response.Chunks[i].Alternatives[j].Text
			}
		}
	}
	return text
}

func main() {

	// defining a struct instance
	var data structure.AutoGenerated

	file, err := ioutil.ReadFile("text.json")

	if err != nil {
		fmt.Println("FileReading err: ")
		fmt.Println(err)
	}

	err = json.Unmarshal([]byte(file), &data)

	if err != nil {
		fmt.Println("Converting err: ")
		fmt.Println(err)
	}
	text := getText(data)

	fmt.Println(text)

	ioutil.WriteFile("result.txt", []byte(text), 0644)
}
