package structure

import (
	"time"
)

type AutoGenerated struct {
	Done     bool `json:"done"`
	Response struct {
		Type   string `json:"@type"`
		Chunks []struct {
			Alternatives []struct {
				Words []struct {
					StartTime  string `json:"startTime"`
					EndTime    string `json:"endTime"`
					Word       string `json:"word"`
					Confidence int    `json:"confidence"`
				} `json:"words"`
				Text       string `json:"text"`
				Confidence int    `json:"confidence"`
			} `json:"alternatives"`
			ChannelTag string `json:"channelTag"`
		} `json:"chunks"`
	} `json:"response"`
	ID         string    `json:"id"`
	CreatedAt  time.Time `json:"createdAt"`
	CreatedBy  string    `json:"createdBy"`
	ModifiedAt time.Time `json:"modifiedAt"`
}
